spring:
  application:
    name: book-knowldge-app

  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: samixsolutions247@gmail.com
    password: kkof xjpk iaam kkeh
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#server:
#  reactive:
#    session:
#      timeout: 120s
#  webflux:
#    session:
#      timeout: 120s

#api:
#    key: ${API_KEY}
#    key2: ${API_KEY2}
api:
  key: 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
  key2: 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
